kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flapp-operator-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: flapp-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flapp-operator-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
