kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flapp-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: flapp-operator
roleRef:
  kind: Role
  name: flapp-operator
  apiGroup: rbac.authorization.k8s.io
---
