apiVersion: fedlearner.k8s.io/v1alpha1
kind: FLApp
metadata:
  name: longrun
  namespace: leader
spec:
  flReplicaSpecs:
    Master:
      pair: true
      replicas: 2
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: longrun
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
    PS:
      pair: false
      replicas: 2
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
    Worker:
      pair: true
      replicas: 3
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: longrun
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
  role: Leader
